export { default as loansCardReducer } from './widgets/LoansCard/state/reducer';
export { default as documentCardReducer } from './widgets/DocumentCard/state/reducer';
export { default as acquisitionCardReducer } from './widgets/ACQRequestsCard/state/reducer';
export { default as illCardReducer } from './widgets/ILLCard/state/reducer';
export { default as overbookedDocumentsReducer } from './lists/OverbookedDocumentsList/state/reducer';
export { default as overdueLoansReducer } from './lists/OverdueLoansList/state/reducer';
export { default as pendingOverdueDocumentsReducer } from './lists/PendingOverdueDocumentsList/state/reducer';
export { default as idleLoansReducer } from './lists/IdleLoansList/state/reducer';
export { default as renewedLoansReducer } from './lists/RenewedLoansList/state/reducer';
